In [ ]:
import numpy as np

# 배열의 정보 확인

In [ ]:
A = np.array([1, 2, 3, 4])

print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print(B.ndim)
print(B.shape)

2
(3, 2)


# 행렬의 내적

2차원 배열인 행렬의 내적을 구하는 방법
$$
\begin{pmatrix}
a & b \\
c & d \\
\end{pmatrix}
\cdot
\begin{pmatrix} 
p & q \\
r & s \\
\end{pmatrix}
= \begin{pmatrix} 
ap+br & aq+bs \\
cp+dr & cq+ds \\
\end{pmatrix}
$$

행렬의 내적은
  * 왼쪽 행렬의 행(가로)과 오른쪽 행렬의 열(세로)을 원소 별로 곱하고 그 값들을 더한다.
  * 계산의 결과가 새로운 다차원 배열의 원소가 된다.
  * 행렬은 보통 대문자로 표기하는 것이 관례

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A.shape : {}".format(A.shape))
print("B.shape : {}".format(B.shape))

A.shape : (2, 2)
B.shape : (2, 2)


In [ ]:
print(np.dot(A, B))
print()
print(A @ B)

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


### 행렬 내적의 특징

* 교환 법칙이 성립되지 않는다.

$$
A \cdot B \ne B \cdot A
$$

In [ ]:
B @ A

array([[23, 34],
       [31, 46]])

# 행과 열의 개수가 다른 상태에서의 행렬 내적
첫 번째 행렬의 1 번째 차원의 원소 수(열의 수)와 두 번째 행렬의 0번째 차원의 원소수 ( 행의 수)가 일치해야 한다.

In [ ]:
A = np.arange(1, 7).reshape( 2, 3 )
B = np.arange(1, 7).reshape( 3, 2)

print(A.shape)
print(B.shape)

(2, 3)
(3, 2)


In [ ]:
A @ B

array([[22, 28],
       [49, 64]])

In [ ]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [ ]:
C = np.arange(1, 5).reshape(2, 2)

print(A.shape)
print(C.shape)

(2, 3)
(2, 2)


In [ ]:
# A @ C

ValueError: ignored

In [ ]:
print(C.shape)
print(A.shape)

(2, 2)
(2, 3)


In [ ]:
C @ A

array([[ 9, 12, 15],
       [19, 26, 33]])

# 차원 수가 달라도 계산은 가능하다.

In [ ]:
A = A.reshape(3, 2)
B = np.array([7, 8])

print(A.shape)
print(B.shape)

(3, 2)
(2,)


In [ ]:
A @ B

array([23, 53, 83])

In [ ]:
B @ A

ValueError: ignored