# Tensorflow란?
* `Tensor`(다차원 배열)이 `Flow`(흘러간다)
  * 1 Rank Tensor : 1차원 배열 (벡터)
  * 2 Rank Tensor : 2차원 배열 (행렬)
  * 3 Rank Tensor : Tensor
* 만들어진 계산그래프에 텐서를 흘려 보내기 때문에 텐서플로우
  * 계산할 내용들을 미리 정리를 해 놓고, 실제 계산이 필요한 순간(훈련)에 데이터(배열)를 흘려 보낸다.

**Tensorflow 2.0 기본 사용 방법**

In [ ]:
import numpy as np
import tensorflow as tf

# Tensor 만들기

`tf.constant()`
  * list -> Tensor

In [ ]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

* tuple -> Tensor

In [ ]:
tf.constant(((1, 2, 3),
             (4, 5, 6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

* ndarray -> Tensor

In [ ]:
arr = np.array([1, 2, 3])
tf.constant(arr)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

# Tensor 정보 확인

In [ ]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

**shape 확인하기**

In [ ]:
tensor.shape

TensorShape([3])

**dtype 확인하기**

In [ ]:
tensor.dtype

tf.int32

Tensor를 생성하면서 dtype 정의해 주기

In [ ]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor.dtype

tf.float32

In [ ]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

Tensor의 `dtype` 변환하기
  * `numpy`에서는 `astype` 사용
  * `tensorflow`에서는 `cast` 사용 

In [ ]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

Tensor에서 numpy 배열 불러오기

In [ ]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [ ]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

# Tensorflow 난수 생성

* `numpy`에서의 정규분포 : `np.random.randn`
* `tensorflow`에서의 정규분포 : `tf.random.normal`

In [ ]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7629174 , -1.2185317 , -0.36094898],
       [-0.5175262 , -0.9445622 ,  0.530065  ],
       [ 1.6471229 , -2.6125846 ,  1.804491  ]], dtype=float32)>

In [ ]:
# 균등분포
tf.random.uniform([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.9956112 , 0.71150506, 0.4025135 ],
       [0.98455834, 0.9207927 , 0.27314007],
       [0.25714338, 0.16061115, 0.7902616 ]], dtype=float32)>

# Tensorflow 배열은 수정 불가!
반드시 `tensorflow`의 `session`의 `Variable`만 수정 가능!

In [ ]:
tensor[0] = 1 # 불가능!!!

TypeError: ignored