In [ ]:
# numpy 모듈 불러오기
import numpy as np

* numpy는 기본적으로 C언어로 구현되어 있습니다. - 속도가 빠르다.
* 수치 연산에 관련된 방대한 라이브러리가 존재. ( with scipy )
* 일반 파이썬을 이용한 수치 연산보다 훨씬 빠르다.
* 특히 배열 병렬 연산에 특화 되어 있다.

# 1. numpy의 배열을 ndarray라고 합니다.

In [ ]:
# ndarray 만들기
# 1. python의 list를 ndarray화 하기
py_list = [1, 2, 3]
arr1 = np.array(py_list) # np.array 함수를 이용해서 ndarray 생성 가능
arr1

array([1, 2, 3])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1[0], arr1[2]

(1, 3)

## 배열의 종류
1. 스칼라(scalar)
  * 0차원 데이터
  * 측정한 하나의 값
    - ```python
        height = 180.1
        age = 34
        weight = 80.5
      ```
2. 벡터(vector)
  * 1차원 배열
  * **스칼라가 연속적으로 모여있는 것**
  * 3명의 키를 하나의 배열로 모을 수 있겠죠?
    * ```python
        person_heights = [180.1, 173.5, 177.8] # 3차원 벡터
      ```
  * 벡터 내에 데이터가 `N`개가 있으면 `N 차원 벡터`라고 한다.
    - 수학적인 표현
3. 행렬(matrix)
  * 2차원 배열
  * 1차원 배열인 벡터가 여러 개 모여있는 것.
    * ```python
      person_info = [[180.1, 33, 80.5],
                      [175.1, 32, 77.3]]
    ```
4. 텐서(tensor)
  * 3차원 이상의 배열을 의미한다.
  * 3차원 배열은 2차원 배열이 모여있는 것
  * 4차원 배열은 3차원 배열이 모여있는 것
  * `N차원 배열`을 그냥 텐서라고 한다. (`N`이 꼭 3부터는 아님..)
  * 텐서의 개념을 활용하면 모든 배열의 모양을 이야기 할 수 있다.
    - `0 Rank Tensor` - 스칼라
    - `1 Rank Tensor` - 벡터
    - `2 Rank Tensor` - 행렬
    - `3 Rank Tensor` - 3 Rank Tensor...
  * Tensorflow는 뭘까요..?
    - 구글에서 제공하는 딥러닝 프레임워크
    - 미리 준비된 네트워크에 Tensor를 흘린다(flow)



### 번외
프레임워크, 라이브러리, 모듈의 차이점
- 모듈 == 라이브러리
  * 모듈 : 프로그램의 작은 한 조각을 사용할 수 있게 해주는 것
  * 라이브러리 : 부품의 기능들을 모아 놓은 것
* 프레임워크
  - 경기장 같은 느낌
  - 허허벌판에서 축구를 하려고 하면
    * 선도 그어야해, 축구 골대도 세워야해, 풀도 뽑고, 돌도 치우고, 평탄화도 해야하고.. 할게 많죠
  - 축구장가서 축구하면 안될까?
  - Tensorflow라는 프레임워크는?
    - 딥러닝을 손쉽게 구현하기 위한 환경

# numpy 함수 알아보자

## np.arange
* 파이썬의 `range`함수와 매우 흡사

In [ ]:
arr = np.arange(10) # 0 ~ 9 까지 들어있는 정수 배열을 생성
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

리스트와 배열의 차이
* 리스트는 파이썬에 존재하는 모든 것을 담아낼 수가 있다.
  * list -> `["hello", 10, 10.3, True, 함수]`
* 배열은 보통 숫자 데이터만 들어가 있을 때 배열이라고 한다.

## 다차원 배열 만들기
2차원 이상의 배열을 다차원 배열이라고 합니다.
* `np.arange` : 1차원 정수 배열 만들 때 사용
* `np.zeros` : 0으로 채워진 0 벡터(zero-vector)를 만들 때 사용
* `np.ones` : 1로 채워진 1 벡터(one-vector)를 만들 때 사용


In [ ]:
np.zeros(5) # 5가 하나만 들어갔다 -> 0으로 채워진 5 차원 벡터( 1차원 배열 )를 생성

array([0., 0., 0., 0., 0.])

In [ ]:
# zeros, ones 의 매개변수는 텐서의 모양(형상정보 - shape)을 지정
np.zeros((2, 3)) # 2차원 배열을 생성, 1차원 배열이 2개, 1차원 배열에 추가되는 0차원 스칼라가 3개

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 4, 5)) # 3차원 배열을 생성, 2차원 배열이 3개, 1차원 배열이 4개, 0차원 스칼라가 5개

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

5로 채워진 배열을 만들고 싶다

In [ ]:
# np.fives(10)
np.ones(3) * 5

array([5., 5., 5.])

In [ ]:
# np.full을 이용하면 지정한 숫자로 채워진 N차원 배열을 만들 수 있다.
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

# 단위 행렬 만들기
* np.eye
* 단위 행렬 : 대각선 방향의 원소가 1이고, 나머지는 0인 행렬

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 1이 아닌 단위 행렬을 대각 행렬이라고 한다.
np.eye(3) * 3.5

array([[3.5, 0. , 0. ],
       [0. , 3.5, 0. ],
       [0. , 0. , 3.5]])

In [ ]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# 점구간 만들기( 사잇값 만들기 )
* np.linspace

In [ ]:
np.linspace(1, 10, 3) # 1부터 10까지 3개의 숫자를 균등한 구간으로 만든다. -> 2개의 구간이 만들어 진다.

array([ 1. ,  5.5, 10. ])

In [ ]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random을 사용하기 위한 numpy
* 랜덤 배열은 딥러닝에서 매개변수(`가중치`, `편향`)를 초기화 하기 위해서 사용

## np.random.rand
* 완전 랜덤 만들기 ( 정규분포나 균등분포가 아닌 완벽한 랜덤 )

In [ ]:
np.random.rand(2, 3)

array([[-0.17273422, -0.62612572, -1.242988  ],
       [ 0.16492808,  1.54843827,  0.91829046]])

In [ ]:
np.random.rand(2, 3, 4)

array([[[ 0.13545564,  0.55708466,  0.22879402,  0.89540672],
        [-0.47474229,  1.79832334,  0.90620115, -2.12998564],
        [-0.24960131, -0.57959302, -1.35647929, -0.439535  ]],

       [[-1.93394725,  0.67981659, -0.28078743,  0.8011591 ],
        [ 0.63442341, -0.15925233, -0.5833726 , -1.80553117],
        [-0.11108925,  0.89489658, -0.1831179 ,  0.67339034]]])

## np.random.randn
  * 정규분포 랜덤값 만들기

In [ ]:
np.random.randn(16)

array([ 0.6142666 , -0.06922422, -1.27656332,  0.45790615, -2.31787627,
       -0.86846007,  0.05079087,  0.26123682, -0.64263525, -0.31582184,
        0.92502421,  0.98303151, -1.03049826, -1.48640611,  0.07087984,
        0.88847337])

보통 정규 분포 랜덤을 이용해서 딥러닝의 초깃값으로 사용합니다.

## np.random.uniform
* 균등분포 랜덤값 만들기

In [ ]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[1.95843402, 1.30678065, 1.0783804 , 1.76277889, 1.11591409],
       [1.73256672, 1.45403416, 2.06346006, 2.33732363, 2.16393878],
       [1.20820913, 1.44844227, 1.17664309, 2.73141268, 2.07290923],
       [1.76433321, 2.95072528, 1.24934517, 2.8416277 , 2.10996178]])

## 정수 랜덤 샘플링 하기
* `np.random.choice`
* 샘플링 : 전체에서 표본을 추출하는 행위
* 랜덤 샘플링 : 일정한 범위 내에서 필요한 정수를 랜덤으로 추출
* 딥러닝에서는 `mini-batch`를 만들 때 사용합니다.

In [ ]:
np.random.choice(10, size=(2, 3)) # 0 ~ 9 사이의 정수를 랜덤하게 (2, 3) 형태의 배열로 추출

array([[3, 0, 4],
       [5, 6, 6]])

In [ ]:
# 숫자 내에서 랜덤하게 추출할 수도 있지만, 배열 내에서도 추출이 가능하다.
arr = np.arange(1, 6)

np.random.choice(arr, size=(2, 2))

array([[4, 5],
       [3, 5]])

In [ ]:
# 중복 추출 하지 않기
np.random.choice(arr, size=(2, 2), replace=False) # replace가 False면 중복 추출 X

array([[2, 3],
       [5, 1]])

## 랜덤 정수 배열 만들기
* `np.random.randint`

In [ ]:
arr1 = np.random.randint(1, 100, size=(5, ))
arr1

array([15, 44, 64, 54, 82])

In [ ]:
arr2 = np.random.randint(1, 100, size=(5, 1))
arr2

array([[34],
       [ 3],
       [28],
       [92],
       [ 8]])

arr1과 arr2는 같은 배열까요? `No`
  * arr1은 1차원 배열, arr2는 2차원 배열

arr1과 arr2는 같은 **벡터**일까요? `Yes`
  * arr1은 numpy에서는 행벡터의 모양을 하고 있지만 실제로는 열벡터이다.
  * arr2는 열의 수가 1개의 열벡터의 모양을 하고 있다.

대부분의 머신러닝 라이브러리는 기본적인 데이터 취급을 열벡터로 하기 때문에 2차원 배열 이상부터 취급이 가능


# axis 이해하기
axis : 축. 축이란? 데이터가 추가되는 방향의 **인덱스**

예를 들어 3차원 배열 (3, 4, 5)
  * 3차원 배열에 추가되는건 2차원 배열 -> `axis : 0`
  * 2차원 배열에 추가되는건 1차원 배열 -> `axis : 1`
  * 1차원 배열에 추가되는건 0차원 스칼라 -> `axis : 2`


In [ ]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
# 축별 최댓값 뽑아내기 (max)
np.max(arr, axis=0)

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=1)

array([[10, 11, 12],
       [22, 23, 24],
       [34, 35, 36]])

In [ ]:
np.max(arr, axis=2)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [ ]:
arr = np.random.randint(1, 37, size=(3,4,3))
arr

array([[[14, 16, 31],
        [25, 19,  2],
        [17, 18, 29],
        [27, 12, 32]],

       [[34, 18,  2],
        [ 4, 12, 11],
        [22, 19, 30],
        [10, 10, 17]],

       [[31,  7, 18],
        [30,  7,  5],
        [12, 23, 29],
        [20,  9,  7]]])

In [ ]:
np.max(arr, axis=0)

array([[34, 18, 31],
       [30, 19, 11],
       [22, 23, 30],
       [27, 12, 32]])

# 인덱스와 슬라이싱

In [ ]:
arr = np.arange(1, 11).reshape(2, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[0][3]

4

In [ ]:
arr[0, 3]

4

특정 차원의 배열을 전체 선택하기 위해서 쓰는 연산자 `:`

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr[:, 2]

array([3, 8])

In [ ]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [ ]:
arr[1, 1:3]

array([[16, 17, 18],
       [19, 20, 21]])

In [ ]:
arr[:, 1:3, :2]

array([[[ 4,  5],
        [ 7,  8]],

       [[16, 17],
        [19, 20]],

       [[28, 29],
        [31, 32]]])

In [ ]:
arr = np.arange(36).reshape(2, 3, 3, 2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [ ]:
arr[0, :, :, 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [ ]:
# 3차원, 0차원 제외하고 1, 2차원 데이터 전체를 가지고 오고 싶다.
# 스프레드 연산자( ... )
arr[0, ... , 0] # 3차원과 0차원 사이에 있는 모든 데이터를 선택

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

보통 이미지 데이터를 딥러닝에서 사용하고자 할 때 : `(N, H, W, C)`
* `N` : 이미지의 개수
* `H` : 세로 픽셀의 개수
* `W` : 가로 픽셀의 개수
* `C` : 채널수 (컬러 RGB : 3, 흑백 GRAYSCALE : 1)

In [ ]:
# 예를 들어 가지고 온 이미지 데이터의 모양이 (60000. 28, 28, 1)
#  이미지가 60,000장이 있다.
#  이미지의 세로 크기는 28px
#  이미지의 가로 크기는 28px
#  이미지의 채널은 1채널(grayscale)

# 한장의 흑백 이미지를 그릴 때 필요한 정보는 단순하게 세로, 가로 픽셀의 정보만 있으면 된다.
# images[0, ..., 0] -> ( 28, 28 )

# 배열의 차원과 형상
* 형상(`shape`)
* 차원수(`ndim`)

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(3, 4)

# 차원수 확장하기
* 보통 딥러닝에서 이미지 분석을 하기 위해 `CNN`알고리즘을 활용합니다.
* `CNN`에 필요한 데이터의 형상이 따로 존재하는데, 이 알고리즘을 활용하기 위한 형상(shape)이 존재 한다.
* `(N, H, W, C)`의 형식을 유지해야 한다.
  * `N` : 이미지의 개수(`BATCH_SIZE`)
  * `H` : 이미지의 세로 픽셀
  * `W` : 이미지의 가로 픽셀
  * `C` : 이미지의 채널 수 (컬러 : 3, 흑백 : 1)
----
예를 들어 흑백 이미지를 수집 했는데, 이 이미지의 형상 정보(shape)를 확인해 보니 `(28,28)`이라면, CNN 알고리즘에 이미지를 집어 넣기 위해서는 `(1, 28, 28, 1)`의 형태로 만들어 줘야 한다.

* numpy의 `np.newaxis`
* tensorflow의 `tf.newaxis`

In [ ]:
arr = np.random.rand(28, 28)
arr.shape

(28, 28)

`(28, 28)` 형식의 배열은 `(H, W)`정보만 존재하고 있는 형태 -> `(1, 28, 28, 1)`형태로 만들어 줘야 CNN 레이어에 입력이 가능하다.

In [ ]:
temp_arr = arr[np.newaxis, :, :, np.newaxis ]
temp_arr.shape

(1, 28, 28, 1)

In [ ]:
temp_arr = arr[np.newaxis, ..., np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

# 차원 쥐어 짜기
* `np.squeeze`
* 개수가 1인 차원의 내용을 없애는 기법

In [ ]:
temp_squeeze = np.squeeze(temp_arr)
temp_squeeze.shape

(28, 28)

# 배열의 형상 바꾸기
* `np.newaxis`를 활용하면 축을 하나 추가하게 된다.( 차원 수를 늘린다. )
* `np.squeeze`를 활용하면 개수가 1인 차원의 데이터를 삭제(차원 수를 줄인다.)

평탄화 : 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것 (★★★★★)
* `ravel` : 원본 배열을 평탄화 시킨 **참조**배열을 만들어 낸다. (이를 View 또는 Reference라고 한다.)
* `flatten` : 원본 배열을 평탄화 시킨 **복사된**배열을 만들어 낸다.

ravel은 원본 배열에 수정이 가해질 가능성이 있고, flatten은 원본 배열에 영향을 미치지 않는다.

In [ ]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [ ]:
x

array([[ 9, 13,  1,  0,  5],
       [14,  6,  8,  3,  9],
       [10,  7, 14, 13,  4]])

## ravel

In [ ]:
temp = np.ravel(x)
temp.shape

(15,)

In [ ]:
temp

array([ 9, 13,  1,  0,  5, 14,  6,  8,  3,  9, 10,  7, 14, 13,  4])

In [ ]:
temp[0] = 100
temp

array([100,  13,   1,   0,   5,  14,   6,   8,   3,   9,  10,   7,  14,
        13,   4])

In [ ]:
x

array([[100,  13,   1,   0,   5],
       [ 14,   6,   8,   3,   9],
       [ 10,   7,  14,  13,   4]])

In [ ]:
x[1][3] = 50000
temp

array([  100,    13,     1, 10000,     5,    14,     6,     8, 50000,
           9,    10,     7,    14,    13,     4])

## flatten

In [ ]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [ ]:
temp_flatten = x.flatten()
temp_flatten.shape

(15,)

In [ ]:
temp_flatten

array([10,  5,  2,  1, 14,  3,  3, 12,  1, 11,  5,  2,  8,  9,  5])

In [ ]:
# flatten은 x를 '복사'해서 새롭게 평탄화된 배열을 만들기 때문에
# 바꿔도 원본엔 영향을 미치지 않는다.
temp_flatten[0] = 100
x

array([[10,  5,  2,  1, 14],
       [ 3,  3, 12,  1, 11],
       [ 5,  2,  8,  9,  5]])

데이터를 안전하게 관리하기 위해서 ravel 보다 flatten을 많이 사용한다.

# reshape
배열의 형상을 재구성하는 것

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

reshape 팁 : reshape 함수 내의 모든 숫자를 곱했을 때 스칼라 원소의 개수와 같아야 한다.

In [ ]:
x.reshape(2, 5, 2) # 가능?

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [ ]:
x.reshape(3, 5, 1) # 가능?

ValueError: ignored

-1을 사용하면 남은 숫자를 자동으로 계산해 준다.

In [ ]:
x.reshape(2, -1, 2) # -1 위치의 값이 알아서 계산된다. 즉 5로 자동 지정됨

In [ ]:
x.reshape(2, 2, -1)

In [ ]:
x.reshape(2, 3, -1) # 안됨.

In [ ]:
x.reshape(2, -1, -1) # 안됨. -1은 하나만 쓸수 있다. 뭐가 어떻게 지정될지 어떻게 알아요..ㅠㅠ

In [ ]:
# 배열의 스칼라의 개수를 구할 때는 size를 활용하면 됩니다.
x.size

# 브로드캐스팅
* 차원 수가 다른 배열끼리 연산
* 차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능
* 저차원 배열을 고차원 배열로 **확장**
* 수학적으로 따지게 되면, 고차원 배열의 shape과 똑같은 1벡터(ones)를 만들어서 저차원 배열과 곱한 배열을 만들어서 계산

In [ ]:
x = np.arange(20).reshape(4, 5)
y = np.arange(20, 40).reshape(4, 5)

x.shape, y.shape

((4, 5), (4, 5))

In [ ]:
x + y

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [ ]:
x * y

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [ ]:
# shape이 다를 때의 연산
a = np.arange(12).reshape(4, 3) # (4, 3)
b = np.arange(100, 103)         # (3, )
c = np.arange(1000, 1004)       # (4, )
d = b.reshape(1, 3)             # (1, 3)
e = np.arange(0, 4).reshape(4, 1) # ( 4, 1)


In [ ]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + c

ValueError: ignored

In [ ]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [ ]:
a + e

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

# 전치행렬 만들기
* 행렬 $A$의 행과 열의 인덱스를 바꾼 것을 전치행렬이라고 한다.
* $A_{(i, j)}$의 인덱스의 위치를 $A_{(j, i)}$로 바꾼 것
* Transpose 라고 합니다.

In [ ]:
A = np.arange(6).reshape(2, 3)
A

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# ndarray 에서 .T만 사용하면 전치행렬 만들 수 있다.
A.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
# 벡터의 전치는 가능 할까요..?
A = np.arange(6)
A

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 1차원 배열은 전치가 되지 않는다.
A.T

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 열 벡터를 전치 시키려면
A = A.reshape(6, 1) # 2차원 배열 형태로 열 벡터를 표현해야 한다.
A

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
A.T

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
import numpy as np
np.random.seed(42)
arr = np.random.randint(1, 100, (3, 4, 3))

In [ ]:
# 빨간 칸
print("빨간 칸 : \n{}".format(arr[::2,:2, :2]))
print()
print("파란 칸 : \n{}".format(arr[:, ::2, :2]))

빨간 칸 : 
[[[52 93]
  [72 61]]

 [[76 58]
  [89 49]]]

파란 칸 : 
[[[52 93]
  [83 87]]

 [[ 3 22]
  [38  2]]

 [[76 58]
  [59 42]]]


In [ ]:
# 파란 칸
arr[:, ::2, :2]

array([[[52, 93],
        [83, 87]],

       [[ 3, 22],
        [38,  2]],

       [[76, 58],
        [59, 42]]])